"""create transactions table

Revision ID: 6c920828053f
Revises: 
Create Date: 2026-03-10 15:17:05.600337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c920828053f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('result_currency', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('total_currency', sa.String(), nullable=True),
    sa.Column('withholding_tax', sa.Float(), nullable=True),
    sa.Column('withholding_tax_currency', sa.String(), nullable=True),
    sa.Column('fx_fee', sa.Float(), nullable=True),
    sa.Column('fx_fee_currency', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('merchant_category', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('parse_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
