"""add t212_id column

Revision ID: ae22b9ad0151
Revises: 1f238c1f4a6b
Create Date: 2026-03-13 13:37:44.727580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae22b9ad0151'
down_revision: Union[str, None] = '1f238c1f4a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('t212_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_t212_id'), 'transactions', ['t212_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_t212_id'), table_name='transactions')
    op.drop_column('transactions', 't212_id')
    # ### end Alembic commands ###
